### ISSUE TITLE
Array element with a sequence

### ISSUE THREAD

**Issue by izk8** [siyuanzhao/automated-essay-grading#4]
Followed the instructions. Using: 
	python2.7
	tensorflow 1.3
	Ubuntu 16.04 
	sklean 19.1 

I can show the versions of the rest of the packages if that would help. 

Got this error: 

```
Traceback (most recent call last):
  File "cv_train.py", line 245, in <module>
    sess.run(tf.global_variables_initializer(), feed_dict={model.w_placeholder: word2vec})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 937, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

any suggestions would be helpful.

**Comment by izk8** [comment]
I am going to do version checks of the stuff in the meantime inside of a virtualenv. It may be as simple as  tensorflow 1 vs tensorflow 1.3

**Comment by izk8** [comment]
Here is the traceback with tensorflow 1.4

```Traceback (most recent call last):
  File "cv_train.py", line 238, in <module>
    memory_size, embedding_size, len(score_range), feature_size, hops, reader, l2_lambda)
  File "/home/isaac/00_Git/automated-essay-grading/memn2n_kv_regression.py", line 155, in __init__
    o = self._key_addressing(doc_r, value_r, q_r, r_list)
  File "/home/isaac/00_Git/automated-essay-grading/memn2n_kv_regression.py", line 253, in _key_addressing
    self.mem_attention_probs = tf.pack(self.mem_attention_probs, axis=1)
AttributeError: 'module' object has no attribute 'pack'
```

and found this answer: 
"As far as I know, tf.pack has been renamed as tf.stack"

Additional validation that tf needs to be downgraded.

**Comment by izk8** [comment]
Changed tf.pack to tf.stack. Also changed tf.sub to tf.subtract.

**Comment by siyuanzhao** [comment]
Please try tf 1.0. The code was developed and tested under that version.

**Comment by izk8** [comment]
Thanks for jumping in! I am really excited to see your code in action. I am currently using tf version 1.0.1:
```
print tf.__version__
1.0.1
```
