### ISSUE TITLE
AttributeError: _parse_flags in __getattr__

### ISSUE THREAD

**Issue by arushi-08** [siyuanzhao/automated-essay-grading#5]
After running `python cv_train.py --essay_set_id 1` in terminal, I get this error:
```
Traceback (most recent call last):
  File "cv_train.py", line 35, in <module>
    FLAGS._parse_flags()
  File "/home/aruhi/tensorflow/venv/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/home/aruhi/tensorflow/venv/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 470, in __getattr__
    raise AttributeError(name)
AttributeError: _parse_flags
```

**Comment by siyuanzhao** [comment]
should be fixed now.
